// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ticker/:hubUrl": {
    params: {
      "hubUrl": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/ticker/:hubUrl";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./ticker/Sports-Ticker.tsx": {
    id: "ticker/Sports-Ticker";
    page: "/ticker/:hubUrl";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "ticker/Sports-Ticker": typeof import("./app/./ticker/Sports-Ticker.tsx");
};